mongo-db:
  build: ./db-server
  #image: rmelos/backautenticacionarquitectura
  ports:
    - 27017:27017
  hostname: mongodbhost

app-ms:
  build: .
  #image: rmelos/backautenticacionarquitectura
  ports:
    - "5000:5000"
  links:
    - mongo-db


